// User types

export const USER_REGISTER_ERRORS = "USER_REGISTER_ERRORS";
export const USER_LOGIN_ERRORS = "USER_LOGIN_ERRORS";
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
